# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/simple.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/simple.proto',
  package='simple',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12proto/simple.proto\x12\x06simple\"*\n\rSimpleRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"#\n\x0eSimpleResponse\x12\x11\n\treply_msg\x18\x01 \x01(\t\"\x1a\n\x0b\x44ictRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"s\n\x0c\x44ictResponse\x12\x33\n\x08reply_kv\x18\x01 \x03(\x0b\x32!.simple.DictResponse.ReplyKvEntry\x1a.\n\x0cReplyKvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1a\n\x0bListRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\"\n\x0cListResponse\x12\x12\n\nreply_list\x18\x01 \x03(\t2\xc0\x01\n\rSimpleService\x12=\n\nSimpleSend\x12\x15.simple.SimpleRequest\x1a\x16.simple.SimpleResponse\"\x00\x12\x37\n\x08ListSend\x12\x13.simple.ListRequest\x1a\x14.simple.ListResponse\"\x00\x12\x37\n\x08\x44ictSend\x12\x13.simple.DictRequest\x1a\x14.simple.DictResponse\"\x00\x62\x06proto3'
)




_SIMPLEREQUEST = _descriptor.Descriptor(
  name='SimpleRequest',
  full_name='simple.SimpleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='simple.SimpleRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='simple.SimpleRequest.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=72,
)


_SIMPLERESPONSE = _descriptor.Descriptor(
  name='SimpleResponse',
  full_name='simple.SimpleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_msg', full_name='simple.SimpleResponse.reply_msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=109,
)


_DICTREQUEST = _descriptor.Descriptor(
  name='DictRequest',
  full_name='simple.DictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='simple.DictRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=137,
)


_DICTRESPONSE_REPLYKVENTRY = _descriptor.Descriptor(
  name='ReplyKvEntry',
  full_name='simple.DictResponse.ReplyKvEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='simple.DictResponse.ReplyKvEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='simple.DictResponse.ReplyKvEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=254,
)

_DICTRESPONSE = _descriptor.Descriptor(
  name='DictResponse',
  full_name='simple.DictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_kv', full_name='simple.DictResponse.reply_kv', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DICTRESPONSE_REPLYKVENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=254,
)


_LISTREQUEST = _descriptor.Descriptor(
  name='ListRequest',
  full_name='simple.ListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='simple.ListRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=282,
)


_LISTRESPONSE = _descriptor.Descriptor(
  name='ListResponse',
  full_name='simple.ListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_list', full_name='simple.ListResponse.reply_list', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=318,
)

_DICTRESPONSE_REPLYKVENTRY.containing_type = _DICTRESPONSE
_DICTRESPONSE.fields_by_name['reply_kv'].message_type = _DICTRESPONSE_REPLYKVENTRY
DESCRIPTOR.message_types_by_name['SimpleRequest'] = _SIMPLEREQUEST
DESCRIPTOR.message_types_by_name['SimpleResponse'] = _SIMPLERESPONSE
DESCRIPTOR.message_types_by_name['DictRequest'] = _DICTREQUEST
DESCRIPTOR.message_types_by_name['DictResponse'] = _DICTRESPONSE
DESCRIPTOR.message_types_by_name['ListRequest'] = _LISTREQUEST
DESCRIPTOR.message_types_by_name['ListResponse'] = _LISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleRequest = _reflection.GeneratedProtocolMessageType('SimpleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEREQUEST,
  '__module__' : 'proto.simple_pb2'
  # @@protoc_insertion_point(class_scope:simple.SimpleRequest)
  })
_sym_db.RegisterMessage(SimpleRequest)

SimpleResponse = _reflection.GeneratedProtocolMessageType('SimpleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLERESPONSE,
  '__module__' : 'proto.simple_pb2'
  # @@protoc_insertion_point(class_scope:simple.SimpleResponse)
  })
_sym_db.RegisterMessage(SimpleResponse)

DictRequest = _reflection.GeneratedProtocolMessageType('DictRequest', (_message.Message,), {
  'DESCRIPTOR' : _DICTREQUEST,
  '__module__' : 'proto.simple_pb2'
  # @@protoc_insertion_point(class_scope:simple.DictRequest)
  })
_sym_db.RegisterMessage(DictRequest)

DictResponse = _reflection.GeneratedProtocolMessageType('DictResponse', (_message.Message,), {

  'ReplyKvEntry' : _reflection.GeneratedProtocolMessageType('ReplyKvEntry', (_message.Message,), {
    'DESCRIPTOR' : _DICTRESPONSE_REPLYKVENTRY,
    '__module__' : 'proto.simple_pb2'
    # @@protoc_insertion_point(class_scope:simple.DictResponse.ReplyKvEntry)
    })
  ,
  'DESCRIPTOR' : _DICTRESPONSE,
  '__module__' : 'proto.simple_pb2'
  # @@protoc_insertion_point(class_scope:simple.DictResponse)
  })
_sym_db.RegisterMessage(DictResponse)
_sym_db.RegisterMessage(DictResponse.ReplyKvEntry)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQUEST,
  '__module__' : 'proto.simple_pb2'
  # @@protoc_insertion_point(class_scope:simple.ListRequest)
  })
_sym_db.RegisterMessage(ListRequest)

ListResponse = _reflection.GeneratedProtocolMessageType('ListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESPONSE,
  '__module__' : 'proto.simple_pb2'
  # @@protoc_insertion_point(class_scope:simple.ListResponse)
  })
_sym_db.RegisterMessage(ListResponse)


_DICTRESPONSE_REPLYKVENTRY._options = None

_SIMPLESERVICE = _descriptor.ServiceDescriptor(
  name='SimpleService',
  full_name='simple.SimpleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=321,
  serialized_end=513,
  methods=[
  _descriptor.MethodDescriptor(
    name='SimpleSend',
    full_name='simple.SimpleService.SimpleSend',
    index=0,
    containing_service=None,
    input_type=_SIMPLEREQUEST,
    output_type=_SIMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListSend',
    full_name='simple.SimpleService.ListSend',
    index=1,
    containing_service=None,
    input_type=_LISTREQUEST,
    output_type=_LISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DictSend',
    full_name='simple.SimpleService.DictSend',
    index=2,
    containing_service=None,
    input_type=_DICTREQUEST,
    output_type=_DICTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMPLESERVICE)

DESCRIPTOR.services_by_name['SimpleService'] = _SIMPLESERVICE

# @@protoc_insertion_point(module_scope)
